sudo systemctl disable hive-server
sudo systemctl disable hadoop
sudo systemctl disable flume
sudo systemctl disable kafka
sudo systemctl disable nginx
sudo systemctl disable logstash
sudo systemctl disable elasticsearch
sudo systemctl disable kibana
sudo systemctl disable zookeper
