sudo systemctl disable hadoop
sudo systemctl enable hive-server
sudo systemctl enable hadoop
sudo systemctl enable flume
sudo systemctl enable kafka
sudo systemctl enable nginx
sudo systemctl enable logstash
sudo systemctl enable elasticsearch
sudo systemctl enable kibana
sudo systemctl enable zookeper
